openapi: 3.0.0
info:
  version: '1.0.0'
  title: 'loan application system'
  description: 'loanapplicationsystem openAPI'
host: localhost
# Added by API Auto Mocking Plugin
servers:
  # Added by API Auto Mocking Plugin
  - description: local
    url: http://localhost/
paths:
  /loan/calculate:
    post:
      post:
      summary: "Calculate credit result and credit limit from specific user information"
      consumes:
        - application/json
       parameters:
        - in: body
          name: userInformation
          type: object
          schema:
            type: object
            properties:
              identificationNo:
                description: identification number of user
                type: String
              name:
                description: name of user
                type: String
              surname:
                description: surname of user
                type: String
              phoneNo:
                description: phone number of user
                type: String
              monthlyIncome:
                description: monthly income of user
                type: Double
      responses:
        "500":
          description: status 500 comes if user is not logged in
          examples:
            text/plain: Internal Server Error
        "401":
          desciription: status "400" comes if user write missing field
          examples:
            text/plain: Error occured while missing parameter.
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: String
                    description: Loan information results returned successfully.
                  message:
                    type: object
                    properties:
                      creaditResult:
                        description: calculated credit status 
                        type: String 
                      creditLimit:
                         description: calculated credit limit 
                         type: double

